import { Open_Sans } from 'next/font/google';
import './globals.css';
import Header from './components/Header/Header';
import Footer from './components/Footer/Footer';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Coffena',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body
        className={`${openSans.className}, w-screen overflow-x-hidden bg-[#F4F1EE] text-[#404040]`}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
